openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: "{protocol}://{origin}/haribote/api/"
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      origin:
        default: "localhost:3000"
tags:
  - name: auth
    description: 認証系
paths:
  /login:
    post:
      summary: ログイン
      tags:
        - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Auth"
      responses:
        '200':
          description: OK

  /current-user:
    get:
      summary: ログインユーザー情報取得
      tags:
        - auth
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CurrentUser"

  /logout:
    delete:
      summary: ログアウト
      tags:
        - auth
      responses:
        '200':
          description: OK

components:
  schemas:
    Auth:
      description: 認証データ
      type: object
      required:
        - email 
        - password
      properties:
        email:
          type: string
        password:
          type: string
          format: password

    CurrentUser:
      description: ログインユーザー情報
      type: object
      required:
        - email 
        - fullName 
        - isAdmin
      properties:
        email:
          type: string
        fullName:
          type: string
        isAdmin:
          type: boolean

